# common/common
{legacy}: [
  legacy.git
  legacy.curl
  legacy.chibi
  legacy.deno
  legacy.dosfstools
  legacy.dprint
  legacy.eza
  legacy.fd
  legacy.gh
  legacy.gitui
  legacy.go
  # legacy.jdk
  legacy.jdk11
  legacy.google-java-format
  legacy.gopls
  legacy.graphviz
  legacy.jdt-language-server
  legacy.lua-language-server
  legacy.luajitPackages.luarocks
  legacy.marksman
  legacy.markdown-oxide
  legacy.maven
  legacy.mysql84
  legacy.nasm
  legacy.neovim
  legacy.ninja
  legacy.nodejs_24
  legacy.pkgconf
  legacy.qemu
  legacy.ripgrep
  legacy.rm-improved
  legacy.sbcl
  legacy.skim
  legacy.starship
  legacy.stylua
  legacy.taplo
  legacy.wabt
  legacy.wasmtime
  legacy.wget
  legacy.zig
  legacy.zoxide
  legacy.zsh-fast-syntax-highlighting
  legacy.docker
  legacy.meslo-lgs-nf
  legacy.alejandra
  legacy.asm-lsp
  legacy.docker-language-server
  legacy.docker-compose-language-service
  legacy.haskell-language-server
  legacy.vscode-langservers-extracted
  legacy.nil
  legacy.typescript-language-server
  legacy.zls
  legacy.tailwindcss-language-server
  legacy.phpactor
  legacy.obsidian
  legacy.firefox
  legacy.neovide
  legacy.reaper
  legacy.docker
  legacy.zsh
  legacy.binutils
  legacy.libclang
  # legacy.ghostty
]
