[window]
decorations = "None"
option_as_alt = "OnlyLeft"

[scrolling]
history = 300

[font]
normal = { family = "FiraCode Nerd Font" }
size = 12.0
builtin_box_drawing = false

[keyboard]
bindings = [
	# applenotes://showNote?identifier=19C0DA4D-7B19-4179-A189-3724532D0CC4
	{ key = "Enter", mods = "Shift", chars = "\u001b[13;2u" },
]
