tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
brew "exa"
brew "fd"
brew "fzf"
brew "llvm"
brew "lua"
brew "neovim", args: ["HEAD"]
brew "node"
brew "ripgrep"
brew "starship"
brew "wget"
cask "fig"
cask "font-hack-nerd-font"
cask "iterm2"
