tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
brew "exa"
brew "fd"
brew "neovim", args: ["HEAD"]
brew "node"
brew "ripgrep"
brew "rm-improved"
brew "sqlite"
cask "font-sauce-code-pro-nerd-font"
cask "iterm2"
cask "raycast"
