tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/services"
tap "jakehilborn/jakehilborn"
tap "koekeishiya/formulae"
brew "eza"
brew "fd"
brew "gh"
brew "lua"
brew "lua-language-server"
brew "mas"
brew "neovim", args: ["HEAD"]
brew "node"
brew "ripgrep"
brew "rm-improved"
brew "sqlite"
brew "starship"
brew "stylua"
brew "zoxide"
brew "jakehilborn/jakehilborn/displayplacer"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai", args: ["HEAD"]
cask "alacritty"
cask "docker"
cask "font-fira-code-nerd-font"
cask "karabiner-elements"
cask "native-access"
cask "raycast"
cask "rekordbox"
cask "the-unarchiver"
mas "Logic Pro", id: 634148309
