#!/usr/bin/env lua

package.cpath = package.cpath .. ';' .. os.getenv 'HOME' .. '/.local/share/sketchybar_lua/?.so'
print(package.cpath)
package.path = package.path
	.. ';'
	.. os.getenv 'HOME'
	.. '/.config/sketchybar/?/init.lua'
	.. ';'
	.. os.getenv 'HOME'
	.. '/.config/sketchybar/?.lua'
print(package.path)

-- load the sketchybar-package and prepare the helper binaries
require 'init'
