#!/usr/bin/env lua

package.cpath = os.getenv 'SBARLUA_DYLIB_PATH' .. '/lib/lua/5.4/?.so' .. ';' .. package.cpath

local builtin_bar = require 'sbar_lua_conf.sbar_builtin_display'
local external_bars = require 'sbar_lua_conf.sbar_external_display'
