#!/usr/bin/env lua

package.cpath = os.getenv 'SBARLUA_DYLIB_PATH' .. '/lib/lua/5.4/sketchybar.so' .. ';' .. package.cpath

local yabai = require 'actor.helper.yabai'

BAR = require 'sketchybar'
BAR_NAME = 'external_1'
BAR.set_bar_name(BAR_NAME)
DISPLAY_INDEX = yabai.display.external_indices()[1]

local property_list = require 'actor.helper.property'

BAR.bar(property_list.bar_properties)
BAR.default(property_list.default_properties)

BAR.begin_config()

require 'actor.startup'

BAR.hotload(true)
BAR.end_config()

BAR.event_loop()
