#!/bin/bash

# Rusty Sbar Setup Script
# This script sets up the Rust SketchyBar configuration

set -e

echo "🦀 Setting up Rusty Sbar..."

# Check if we're in the right directory
if [ ! -f "Cargo.toml" ]; then
    echo "❌ Error: Please run this script from the sbar-rs directory"
    exit 1
fi

# Build the project
echo "🔨 Building Rust project..."
cargo build --release

# Create SketchyBar config directory if it doesn't exist
SKETCHYBAR_CONFIG_DIR="$HOME/.config/sketchybar"
mkdir -p "$SKETCHYBAR_CONFIG_DIR"

# Create the sketchybarrc file
echo "📝 Creating SketchyBar configuration..."
cat > "$SKETCHYBAR_CONFIG_DIR/sketchybarrc" << EOF
#!/bin/bash

# Rusty Sbar - SketchyBar configuration in Rust
# Generated by setup.sh

exec "$PWD/target/release/sketchybar-config"
EOF

# Make it executable
chmod +x "$SKETCHYBAR_CONFIG_DIR/sketchybarrc"

echo "✅ Setup complete!"
echo ""
echo "📋 Next steps:"
echo "1. Restart SketchyBar: brew services restart sketchybar"
echo "2. Check logs if needed: tail -f /tmp/sketchybar_*.log"
echo ""
echo "🎨 Your new Rust-powered SketchyBar is ready!"
echo "   - Multi-display support ✓"
echo "   - Real-time clock updates ✓"
echo "   - Battery monitoring ✓"
echo "   - Catppuccin theme ✓"
echo ""
echo "🔧 To customize, edit the Rust source files and run:"
echo "   cargo build --release && brew services restart sketchybar"
